# Generated by Django 2.2.8 on 2020-01-11 09:13

from django.db import migrations, models
import django.db.models.deletion
import response.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('response_id', models.CharField(default=response.models.generate_random_string, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('answers', models.ManyToManyField(to='response.Response')),
            ],
        ),
    ]
